//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public string idBaiViet { get; set; }
        public string tenBaiViet { get; set; }
        public string noiDungTomTat { get; set; }
        public string noiDung { get; set; }
        public Nullable<int> luotXem { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public string idTaiKhoanDang { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public string hinhDaiDien { get; set; }
    }
}
