//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaKichHoatTaiKhoan
    {
        public int idMaKichHoat { get; set; }
        public string idTaiKhoan { get; set; }
        public string maKichHoat { get; set; }
        public Nullable<System.DateTime> thoiGianTaoMa { get; set; }
        public Nullable<bool> trangThaiMa { get; set; }
        public string ghiChu { get; set; }
    }
}
