//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeGiay
    {
        public int maSize { get; set; }
        public Nullable<int> size { get; set; }
    }
}
