//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
        }
    
        public string idTaiKhoan { get; set; }
        public string email { get; set; }
        public string soDienThoai { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public string matKhau { get; set; }
        public string matKhauQT { get; set; }
        public int maNhom { get; set; }
        public int sttTrangThai { get; set; }
        public string diaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
    }
}
